id: I22774D44
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T05:48:45+00:00'
last_modified: '2022-06-08T13:36:22.676018+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8036
  title: མ་ཅིག་ལབ་སྒྲོན་གྱི་གསུང་རྣམ། དེབ་དང་པོ་དང་གཉིས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AAA6:
      image_group_id: I3CN8038
      title: ''
      total_pages: 290
      order: 1
      base_file: AAA6.txt
    F27A:
      image_group_id: I3CN8039
      title: ''
      total_pages: 338
      order: 2
      base_file: F27A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
